# Optional user compose overrides for Port.
#
# This file is read by Port and rendered at runtime into:
#   .port/override.user.yml
#
# Supported variables:
#   PORT_ROOT_PATH
#   PORT_WORKTREE_PATH
#   PORT_BRANCH
#   PORT_DOMAIN
#   PORT_PROJECT_NAME
#   PORT_COMPOSE_FILE
#
# Compose precedence (last file wins):
#   1) your base compose file
#   2) .port/override.yml (Port-generated)
#   3) .port/override.user.yml (rendered from this file)
#
# Add overrides below as needed. By default this file has no active changes.

# Example (disabled): add a branch label to web
# services:
#   web:
#     labels:
#       - app.branch=$PORT_BRANCH
#
# Example (disabled): branch-specific hostname rule
# services:
#   web:
#     labels:
#       - traefik.http.routers.$PORT_BRANCH-web.rule=Host(`$PORT_BRANCH.$PORT_DOMAIN`)
#
# Example (disabled): inject branch into container environment
# services:
#   web:
#     environment:
#       PORT_BRANCH_NAME: $PORT_BRANCH
